# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Nex
email: nex@nex.sx
description: > # this means to ignore newlines until "baseurl:"
  The personal website of Claudio Guarnieri, alias Nex.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nex.sx" # the base hostname & protocol for your site
twitter_username: botherder
github_username:  botherder

# Build settings
markdown: kramdown
